let lang=localStorage.getItem('lang')||'zh';
let __geo=null, __ip='未知', __weather=null, __placeZh='', __placeEn='';
const i18n={
 zh:{date:'当前日期',time:'实时时间',timeSub:'上海时区 · 24小时制 · 秒级刷新',weather:'本地天气',projects:'项目展示',ipaddr:'访客 IP 与地址：',fetchFail:'获取失败',locFail:'定位失败',view:'查看项目'},
 en:{date:'Date',time:'Time',timeSub:'Asia/Shanghai · 24h · second refresh',weather:'Local Weather',projects:'Projects',ipaddr:'Visitor IP & Location: ',fetchFail:'Unavailable',locFail:'Location unavailable',view:'View'}
};
const weatherText={0:{zh:'晴',en:'Clear'},1:{zh:'大致晴',en:'Mainly clear'},2:{zh:'局部多云',en:'Partly cloudy'},3:{zh:'阴',en:'Overcast'},45:{zh:'雾',en:'Fog'},48:{zh:'雾凇',en:'Rime fog'},51:{zh:'小毛雨',en:'Light drizzle'},53:{zh:'毛雨',en:'Drizzle'},55:{zh:'浓毛雨',en:'Dense drizzle'},61:{zh:'小雨',en:'Light rain'},63:{zh:'中雨',en:'Rain'},65:{zh:'大雨',en:'Heavy rain'},71:{zh:'小雪',en:'Light snow'},73:{zh:'中雪',en:'Snow'},75:{zh:'大雪',en:'Heavy snow'},80:{zh:'阵雨',en:'Rain showers'},81:{zh:'强阵雨',en:'Heavy showers'},82:{zh:'暴雨',en:'Violent rain'},95:{zh:'雷暴',en:'Thunderstorm'}};
const countryZhMap={JP:'日本',US:'美国',CN:'中国',HK:'中国香港',TW:'中国台湾',SG:'新加坡',KR:'韩国',GB:'英国',DE:'德国',FR:'法国',CA:'加拿大',AU:'澳大利亚',RU:'俄罗斯',IN:'印度',TH:'泰国',MY:'马来西亚',PH:'菲律宾',ID:'印度尼西亚',VN:'越南'};
const weatherIcon={0:'☀️',1:'🌤️',2:'⛅',3:'☁️',45:'🌫️',48:'🌫️',51:'🌦️',53:'🌦️',55:'🌧️',61:'🌦️',63:'🌧️',65:'🌧️',71:'🌨️',73:'❄️',75:'❄️',80:'🌦️',81:'⛈️',82:'⛈️',95:'⛈️'};
function countryName(geo){const code=(geo?.country_code||geo?.country||'').toUpperCase();if(!code) return geo?.country_name||'';if(lang==='zh'&&countryZhMap[code]) return countryZhMap[code];try{const dn=new Intl.DisplayNames([lang==='zh'?'zh-Hans':'en'],{type:'region'});return dn.of(code)||geo?.country_name||code;}catch{return geo?.country_name||code;}}
function placeName(){if(lang==='zh'&&__placeZh) return __placeZh;if(lang==='en'&&__placeEn) return __placeEn;return __geo?.city||__geo?.region||(lang==='zh'?'本地':'Local');}
function applyI18n(){document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;el.textContent=i18n[lang][k]||k;});}
function setLang(l){lang=l;localStorage.setItem('lang',l);applyI18n();loadGeoAndWeather();}
window.setLang=setLang;applyI18n();
fetch('/data/site.json?t='+Date.now()).then(r=>r.json()).then(d=>{for(const k of ['siteTitle','title','subtitle','sectionTitle1','sectionTitle2','sectionTitle3','about1','about2','about3','projectsTitle','contact']){const el=document.getElementById(k);if(el)el.textContent=d[k]||'';}if(d.siteTitle)document.title=d.siteTitle;const list=document.getElementById('projectList');list.innerHTML='';(d.projects||[]).forEach(p=>{const a=document.createElement('article');a.className='proj';a.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px"><strong>${p.name||''}</strong><span class="badge">${p.status||''}</span></div><p class="muted" style="margin:8px 0 10px">${p.desc||''}</p><a href="${p.link||'#'}" target="_blank" rel="noreferrer">${i18n[lang].view}</a>`;list.appendChild(a);});});
function setThemeByShanghai(){const sh=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Shanghai'}));document.body.classList.toggle('day',sh.getHours()>=6&&sh.getHours()<18);}
function renderFlipClock(t){const target=document.getElementById('clockFlip');if(!target.dataset.init){target.innerHTML='';for(const ch of t){if(ch===':'){const c=document.createElement('div');c.className='colon';c.textContent=':';target.appendChild(c);}else{const d=document.createElement('div');d.className='digit';d.innerHTML='<span>'+ch+'</span>';target.appendChild(d);}}target.dataset.init='1';return;}const digits=[...target.querySelectorAll('.digit')];let i2=0;for(const ch of t){if(ch===':')continue;const cell=digits[i2++],sp=cell.querySelector('span');if(sp.textContent!==ch){cell.classList.add('flip');setTimeout(()=>{sp.textContent=ch;cell.classList.remove('flip');},170);}}}
function tick(){const n=new Date();document.getElementById('dateNow').textContent=n.toLocaleDateString(lang==='zh'?'zh-CN':'en-US',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',weekday:'long'});renderFlipClock(n.toLocaleTimeString(lang==='zh'?'zh-CN':'en-US',{timeZone:'Asia/Shanghai',hour12:false}));setThemeByShanghai();}
tick();setInterval(tick,1000);
function renderDynamic(){if(__geo){const city=placeName();const country=countryName(__geo);const region=(lang==='zh'&&__placeZh)?'':(__geo.region||'');document.getElementById('visitorFoot').textContent=`${i18n[lang].ipaddr}${__ip} · ${country}${region?(' / '+region):''}${city?(' / '+city):''}`;}if(__weather){const city=placeName();const txt=(weatherText[__weather.code]?.[lang]) || (lang==='zh'?'天气':'Weather');document.getElementById('weather').textContent=`${city} · ${__weather.temp ?? '--'}°C · ${txt}`;document.getElementById('weatherIcon').textContent=weatherIcon[__weather.code]||'🌡️';}}
async function loadGeoAndWeather(){try{const geoUrl=lang==='zh'?'https://ipapi.co/json/?lang=zh-CN':'https://ipapi.co/json/?lang=en';__geo=await (await fetch(geoUrl)).json();try{const bZh=await (await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${__geo.latitude}&longitude=${__geo.longitude}&localityLanguage=zh`)).json();const bEn=await (await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${__geo.latitude}&longitude=${__geo.longitude}&localityLanguage=en`)).json();__placeZh=bZh?.city||bZh?.locality||bZh?.principalSubdivision||'';__placeEn=bEn?.city||bEn?.locality||bEn?.principalSubdivision||'';}catch{__placeZh='';__placeEn='';}if(__geo.latitude&&__geo.longitude){const w=await (await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${__geo.latitude}&longitude=${__geo.longitude}&current=temperature_2m,weather_code&timezone=auto`)).json();__weather={temp:w?.current?.temperature_2m,code:w?.current?.weather_code};}else{__weather=null;}renderDynamic();if(!__weather)document.getElementById('weather').textContent=i18n[lang].locFail;}catch{document.getElementById('weather').textContent=i18n[lang].fetchFail;document.getElementById('visitorFoot').textContent=`${i18n[lang].ipaddr}${i18n[lang].fetchFail}`;}}
(async function(){try{__ip=(await (await fetch('https://api.ipify.org?format=json')).json()).ip||'未知';await loadGeoAndWeather();}catch{}})();
