services:
  admin:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    container_name: net-page-admin
    restart: unless-stopped
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: change-me-please
    volumes:
      - ./data:/data

  web:
    image: ghcr.io/liang-net/net-page:latest
    container_name: net-page-web
    restart: unless-stopped
    depends_on:
      - admin
    ports:
      - "3838:80"
